In [22]:
import os
import numpy as np
import pandas as pd
home_folder = os.path.expanduser("~")
data_folder = os.path.join(home_folder, "Data", "basketball")
data_folder = os.path.abspath('Data/basketball')
data_filename = os.path.join(data_folder, "leagues_NBA_2014_games_games.csv")

print(data_filename)

F:\Desktop\Learning-Data-Mining-with-Python\Data\basketball\leagues_NBA_2014_games_games.csv

In [23]:
results = pd.read_csv(data_filename)
results

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Start (ET)</th>
      <th>Visitor/Neutral</th>
      <th>PTS</th>
      <th>Home/Neutral</th>
      <th>PTS.1</th>
      <th>Unnamed: 6</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Thu Jun 5 2014</td>
      <td>9:00 PM</td>
      <td>Miami Heat</td>
      <td>95</td>
      <td>San Antonio Spurs</td>
      <td>110</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Sun Jun 8 2014</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>98</td>
      <td>San Antonio Spurs</td>
      <td>96</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Tue Jun 10 2014</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>111</td>
      <td>Miami Heat</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Thu Jun 12 2014</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>107</td>
      <td>Miami Heat</td>
      <td>86</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Sun Jun 15 2014</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>87</td>
      <td>San Antonio Spurs</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Thu May 1 2014</td>
      <td>7:00 PM</td>
      <td>Indiana Pacers</td>
      <td>95</td>
      <td>Atlanta Hawks</td>
      <td>88</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Thu May 1 2014</td>
      <td>10:30 PM</td>
      <td>Los Angeles Clippers</td>
      <td>99</td>
      <td>Golden State Warriors</td>
      <td>100</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Thu May 1 2014</td>
      <td>8:00 PM</td>
      <td>Oklahoma City Thunder</td>
      <td>104</td>
      <td>Memphis Grizzlies</td>
      <td>84</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Fri May 2 2014</td>
      <td>7:00 PM</td>
      <td>Toronto Raptors</td>
      <td>83</td>
      <td>Brooklyn Nets</td>
      <td>97</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Fri May 2 2014</td>
      <td>8:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>111</td>
      <td>Dallas Mavericks</td>
      <td>113</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Fri May 2 2014</td>
      <td>10:30 PM</td>
      <td>Houston Rockets</td>
      <td>98</td>
      <td>Portland Trail Blazers</td>
      <td>99</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Sat May 3 2014</td>
      <td>5:30 PM</td>
      <td>Atlanta Hawks</td>
      <td>80</td>
      <td>Indiana Pacers</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Sat May 3 2014</td>
      <td>10:30 PM</td>
      <td>Golden State Warriors</td>
      <td>121</td>
      <td>Los Angeles Clippers</td>
      <td>126</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Sat May 3 2014</td>
      <td>8:00 PM</td>
      <td>Memphis Grizzlies</td>
      <td>109</td>
      <td>Oklahoma City Thunder</td>
      <td>120</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Sun May 4 2014</td>
      <td>3:30 PM</td>
      <td>Dallas Mavericks</td>
      <td>96</td>
      <td>San Antonio Spurs</td>
      <td>119</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Sun May 4 2014</td>
      <td>1:00 PM</td>
      <td>Brooklyn Nets</td>
      <td>104</td>
      <td>Toronto Raptors</td>
      <td>103</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Mon May 5 2014</td>
      <td>7:00 PM</td>
      <td>Washington Wizards</td>
      <td>102</td>
      <td>Indiana Pacers</td>
      <td>96</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Mon May 5 2014</td>
      <td>9:42 PM</td>
      <td>Los Angeles Clippers</td>
      <td>122</td>
      <td>Oklahoma City Thunder</td>
      <td>105</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>18</th>
      <td>Tue May 6 2014</td>
      <td>7:00 PM</td>
      <td>Brooklyn Nets</td>
      <td>86</td>
      <td>Miami Heat</td>
      <td>107</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>19</th>
      <td>Tue May 6 2014</td>
      <td>9:30 PM</td>
      <td>Portland Trail Blazers</td>
      <td>92</td>
      <td>San Antonio Spurs</td>
      <td>116</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>20</th>
      <td>Wed May 7 2014</td>
      <td>7:00 PM</td>
      <td>Washington Wizards</td>
      <td>82</td>
      <td>Indiana Pacers</td>
      <td>86</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Wed May 7 2014</td>
      <td>9:30 PM</td>
      <td>Los Angeles Clippers</td>
      <td>101</td>
      <td>Oklahoma City Thunder</td>
      <td>112</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>22</th>
      <td>Thu May 8 2014</td>
      <td>7:00 PM</td>
      <td>Brooklyn Nets</td>
      <td>82</td>
      <td>Miami Heat</td>
      <td>94</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>23</th>
      <td>Thu May 8 2014</td>
      <td>9:30 PM</td>
      <td>Portland Trail Blazers</td>
      <td>97</td>
      <td>San Antonio Spurs</td>
      <td>114</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>24</th>
      <td>Fri May 9 2014</td>
      <td>10:30 PM</td>
      <td>Oklahoma City Thunder</td>
      <td>118</td>
      <td>Los Angeles Clippers</td>
      <td>112</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Fri May 9 2014</td>
      <td>8:00 PM</td>
      <td>Indiana Pacers</td>
      <td>85</td>
      <td>Washington Wizards</td>
      <td>63</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>26</th>
      <td>Sat May 10 2014</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>90</td>
      <td>Brooklyn Nets</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>27</th>
      <td>Sat May 10 2014</td>
      <td>10:30 PM</td>
      <td>San Antonio Spurs</td>
      <td>118</td>
      <td>Portland Trail Blazers</td>
      <td>103</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Sun May 11 2014</td>
      <td>3:30 PM</td>
      <td>Oklahoma City Thunder</td>
      <td>99</td>
      <td>Los Angeles Clippers</td>
      <td>101</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>29</th>
      <td>Sun May 11 2014</td>
      <td>8:00 PM</td>
      <td>Indiana Pacers</td>
      <td>95</td>
      <td>Washington Wizards</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1289</th>
      <td>Fri Nov 29 2013</td>
      <td>8:00 PM</td>
      <td>New Orleans Pelicans</td>
      <td>121</td>
      <td>Philadelphia 76ers</td>
      <td>105</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1290</th>
      <td>Fri Nov 29 2013</td>
      <td>10:00 PM</td>
      <td>Los Angeles Clippers</td>
      <td>104</td>
      <td>Sacramento Kings</td>
      <td>98</td>
      <td>OT</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1291</th>
      <td>Fri Nov 29 2013</td>
      <td>7:00 PM</td>
      <td>Miami Heat</td>
      <td>90</td>
      <td>Toronto Raptors</td>
      <td>83</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1292</th>
      <td>Fri Nov 29 2013</td>
      <td>9:00 PM</td>
      <td>Phoenix Suns</td>
      <td>112</td>
      <td>Utah Jazz</td>
      <td>101</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1293</th>
      <td>Sat Nov 30 2013</td>
      <td>7:30 PM</td>
      <td>Chicago Bulls</td>
      <td>93</td>
      <td>Cleveland Cavaliers</td>
      <td>97</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1294</th>
      <td>Sat Nov 30 2013</td>
      <td>8:30 PM</td>
      <td>Minnesota Timberwolves</td>
      <td>112</td>
      <td>Dallas Mavericks</td>
      <td>106</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1295</th>
      <td>Sat Nov 30 2013</td>
      <td>8:00 PM</td>
      <td>Brooklyn Nets</td>
      <td>97</td>
      <td>Memphis Grizzlies</td>
      <td>88</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1296</th>
      <td>Sat Nov 30 2013</td>
      <td>9:00 PM</td>
      <td>Boston Celtics</td>
      <td>85</td>
      <td>Milwaukee Bucks</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1297</th>
      <td>Sat Nov 30 2013</td>
      <td>9:00 PM</td>
      <td>Utah Jazz</td>
      <td>112</td>
      <td>Phoenix Suns</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1298</th>
      <td>Sat Nov 30 2013</td>
      <td>8:30 PM</td>
      <td>Houston Rockets</td>
      <td>112</td>
      <td>San Antonio Spurs</td>
      <td>106</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1299</th>
      <td>Sat Nov 30 2013</td>
      <td>7:00 PM</td>
      <td>Atlanta Hawks</td>
      <td>101</td>
      <td>Washington Wizards</td>
      <td>108</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1300</th>
      <td>Tue Oct 29 2013</td>
      <td>7:00 PM</td>
      <td>Orlando Magic</td>
      <td>87</td>
      <td>Indiana Pacers</td>
      <td>97</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1301</th>
      <td>Tue Oct 29 2013</td>
      <td>10:30 PM</td>
      <td>Los Angeles Clippers</td>
      <td>103</td>
      <td>Los Angeles Lakers</td>
      <td>116</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1302</th>
      <td>Tue Oct 29 2013</td>
      <td>8:00 PM</td>
      <td>Chicago Bulls</td>
      <td>95</td>
      <td>Miami Heat</td>
      <td>107</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1303</th>
      <td>Wed Oct 30 2013</td>
      <td>7:00 PM</td>
      <td>Brooklyn Nets</td>
      <td>94</td>
      <td>Cleveland Cavaliers</td>
      <td>98</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1304</th>
      <td>Wed Oct 30 2013</td>
      <td>8:30 PM</td>
      <td>Atlanta Hawks</td>
      <td>109</td>
      <td>Dallas Mavericks</td>
      <td>118</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1305</th>
      <td>Wed Oct 30 2013</td>
      <td>7:30 PM</td>
      <td>Washington Wizards</td>
      <td>102</td>
      <td>Detroit Pistons</td>
      <td>113</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1306</th>
      <td>Wed Oct 30 2013</td>
      <td>10:30 PM</td>
      <td>Los Angeles Lakers</td>
      <td>94</td>
      <td>Golden State Warriors</td>
      <td>125</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1307</th>
      <td>Wed Oct 30 2013</td>
      <td>8:00 PM</td>
      <td>Charlotte Bobcats</td>
      <td>83</td>
      <td>Houston Rockets</td>
      <td>96</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1308</th>
      <td>Wed Oct 30 2013</td>
      <td>8:00 PM</td>
      <td>Orlando Magic</td>
      <td>115</td>
      <td>Minnesota Timberwolves</td>
      <td>120</td>
      <td>OT</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1309</th>
      <td>Wed Oct 30 2013</td>
      <td>8:00 PM</td>
      <td>Indiana Pacers</td>
      <td>95</td>
      <td>New Orleans Pelicans</td>
      <td>90</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1310</th>
      <td>Wed Oct 30 2013</td>
      <td>7:30 PM</td>
      <td>Milwaukee Bucks</td>
      <td>83</td>
      <td>New York Knicks</td>
      <td>90</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1311</th>
      <td>Wed Oct 30 2013</td>
      <td>7:00 PM</td>
      <td>Miami Heat</td>
      <td>110</td>
      <td>Philadelphia 76ers</td>
      <td>114</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1312</th>
      <td>Wed Oct 30 2013</td>
      <td>10:00 PM</td>
      <td>Portland Trail Blazers</td>
      <td>91</td>
      <td>Phoenix Suns</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1313</th>
      <td>Wed Oct 30 2013</td>
      <td>10:00 PM</td>
      <td>Denver Nuggets</td>
      <td>88</td>
      <td>Sacramento Kings</td>
      <td>90</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1314</th>
      <td>Wed Oct 30 2013</td>
      <td>8:30 PM</td>
      <td>Memphis Grizzlies</td>
      <td>94</td>
      <td>San Antonio Spurs</td>
      <td>101</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1315</th>
      <td>Wed Oct 30 2013</td>
      <td>7:00 PM</td>
      <td>Boston Celtics</td>
      <td>87</td>
      <td>Toronto Raptors</td>
      <td>93</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1316</th>
      <td>Wed Oct 30 2013</td>
      <td>9:00 PM</td>
      <td>Oklahoma City Thunder</td>
      <td>101</td>
      <td>Utah Jazz</td>
      <td>98</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1317</th>
      <td>Thu Oct 31 2013</td>
      <td>8:00 PM</td>
      <td>New York Knicks</td>
      <td>81</td>
      <td>Chicago Bulls</td>
      <td>82</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1318</th>
      <td>Thu Oct 31 2013</td>
      <td>10:30 PM</td>
      <td>Golden State Warriors</td>
      <td>115</td>
      <td>Los Angeles Clippers</td>
      <td>126</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>1319 rows × 8 columns</p>
</div>

In [36]:
# Don't read the first row, as it is blank, and parse the date column as a date
results = pd.read_csv(data_filename, parse_dates=["Date"])
# Fix the name of the columns
results.columns =["Date", "Score Type", "Visitor Team", "VisitorPts", "Home Team", "HomePts", "OT?", "Notes"]

results.iloc[:5]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Score Type</th>
      <th>Visitor Team</th>
      <th>VisitorPts</th>
      <th>Home Team</th>
      <th>HomePts</th>
      <th>OT?</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2014-06-05</td>
      <td>9:00 PM</td>
      <td>Miami Heat</td>
      <td>95</td>
      <td>San Antonio Spurs</td>
      <td>110</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2014-06-08</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>98</td>
      <td>San Antonio Spurs</td>
      <td>96</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2014-06-10</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>111</td>
      <td>Miami Heat</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2014-06-12</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>107</td>
      <td>Miami Heat</td>
      <td>86</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2014-06-15</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>87</td>
      <td>San Antonio Spurs</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

In [38]:
results["HomeWin"] = results["VisitorPts"] < results["HomePts"]
# Our "class values"
y_true = results["HomeWin"].values
results.iloc[:5]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Score Type</th>
      <th>Visitor Team</th>
      <th>VisitorPts</th>
      <th>Home Team</th>
      <th>HomePts</th>
      <th>OT?</th>
      <th>Notes</th>
      <th>HomeWin</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2014-06-05</td>
      <td>9:00 PM</td>
      <td>Miami Heat</td>
      <td>95</td>
      <td>San Antonio Spurs</td>
      <td>110</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2014-06-08</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>98</td>
      <td>San Antonio Spurs</td>
      <td>96</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2014-06-10</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>111</td>
      <td>Miami Heat</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2014-06-12</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>107</td>
      <td>Miami Heat</td>
      <td>86</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2014-06-15</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>87</td>
      <td>San Antonio Spurs</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
    </tr>
  </tbody>
</table>
</div>

In [40]:
print("Home Win percentage: {0:.1f}%".format(100 * results["HomeWin"].sum() / results["HomeWin"].count()))

Home Win percentage: 57.9%

In [43]:
results["HomeLastWin"] = False
results["VisitorLastWin"] = False
# This creates two new columns, all set to False
results.iloc[:5]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Score Type</th>
      <th>Visitor Team</th>
      <th>VisitorPts</th>
      <th>Home Team</th>
      <th>HomePts</th>
      <th>OT?</th>
      <th>Notes</th>
      <th>HomeWin</th>
      <th>HomeLastWin</th>
      <th>VisitorLastWin</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2014-06-05</td>
      <td>9:00 PM</td>
      <td>Miami Heat</td>
      <td>95</td>
      <td>San Antonio Spurs</td>
      <td>110</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2014-06-08</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>98</td>
      <td>San Antonio Spurs</td>
      <td>96</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2014-06-10</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>111</td>
      <td>Miami Heat</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2014-06-12</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>107</td>
      <td>Miami Heat</td>
      <td>86</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2014-06-15</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>87</td>
      <td>San Antonio Spurs</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>False</td>
      <td>False</td>
    </tr>
  </tbody>
</table>
</div>

In [46]:
# Now compute the actual values for these
# Did the home and visitor teams win their last game?
from collections import defaultdict
won_last = defaultdict(int)

for index, row in results.iterrows():  # Note that this is not efficient
    home_team = row["Home Team"]
    visitor_team = row["Visitor Team"]
    row["HomeLastWin"] = won_last[home_team]
    row["VisitorLastWin"] = won_last[visitor_team]
    results.ix[index] = row    
    # Set current win
    won_last[home_team] = row["HomeWin"]
    won_last[visitor_team] = not row["HomeWin"]
results.ix[20:25]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Score Type</th>
      <th>Visitor Team</th>
      <th>VisitorPts</th>
      <th>Home Team</th>
      <th>HomePts</th>
      <th>OT?</th>
      <th>Notes</th>
      <th>HomeWin</th>
      <th>HomeLastWin</th>
      <th>VisitorLastWin</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>20</th>
      <td>2014-05-07</td>
      <td>7:00 PM</td>
      <td>Washington Wizards</td>
      <td>82</td>
      <td>Indiana Pacers</td>
      <td>86</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>False</td>
      <td>True</td>
    </tr>
    <tr>
      <th>21</th>
      <td>2014-05-07</td>
      <td>9:30 PM</td>
      <td>Los Angeles Clippers</td>
      <td>101</td>
      <td>Oklahoma City Thunder</td>
      <td>112</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>False</td>
      <td>True</td>
    </tr>
    <tr>
      <th>22</th>
      <td>2014-05-08</td>
      <td>7:00 PM</td>
      <td>Brooklyn Nets</td>
      <td>82</td>
      <td>Miami Heat</td>
      <td>94</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>True</td>
      <td>False</td>
    </tr>
    <tr>
      <th>23</th>
      <td>2014-05-08</td>
      <td>9:30 PM</td>
      <td>Portland Trail Blazers</td>
      <td>97</td>
      <td>San Antonio Spurs</td>
      <td>114</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>True</td>
      <td>False</td>
    </tr>
    <tr>
      <th>24</th>
      <td>2014-05-09</td>
      <td>10:30 PM</td>
      <td>Oklahoma City Thunder</td>
      <td>118</td>
      <td>Los Angeles Clippers</td>
      <td>112</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
      <td>True</td>
    </tr>
    <tr>
      <th>25</th>
      <td>2014-05-09</td>
      <td>8:00 PM</td>
      <td>Indiana Pacers</td>
      <td>85</td>
      <td>Washington Wizards</td>
      <td>63</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
      <td>True</td>
    </tr>
  </tbody>
</table>
</div>

In [47]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=14)

In [48]:
from sklearn.cross_validation import cross_val_score

# Create a dataset with just the neccessary information
X_previouswins = results[["HomeLastWin", "VisitorLastWin"]].values
clf = DecisionTreeClassifier(random_state=14)
scores = cross_val_score(clf, X_previouswins, y_true, scoring='accuracy')
print("Using just the last result from the home and visitor teams")
print("Accuracy: {0:.1f}%".format(np.mean(scores) * 100))

Using just the last result from the home and visitor teams
Accuracy: 57.2%

E:\Anaconda3\envs\DataMining\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [49]:
# What about win streaks?
results["HomeWinStreak"] = 0
results["VisitorWinStreak"] = 0
# Did the home and visitor teams win their last game?
from collections import defaultdict
win_streak = defaultdict(int)

for index, row in results.iterrows():  # Note that this is not efficient
    home_team = row["Home Team"]
    visitor_team = row["Visitor Team"]
    row["HomeWinStreak"] = win_streak[home_team]
    row["VisitorWinStreak"] = win_streak[visitor_team]
    results.ix[index] = row    
    # Set current win
    if row["HomeWin"]:
        win_streak[home_team] += 1
        win_streak[visitor_team] = 0
    else:
        win_streak[home_team] = 0
        win_streak[visitor_team] += 1

In [50]:
clf = DecisionTreeClassifier(random_state=14)
X_winstreak =  results[["HomeLastWin", "VisitorLastWin", "HomeWinStreak", "VisitorWinStreak"]].values
scores = cross_val_score(clf, X_winstreak, y_true, scoring='accuracy')
print("Using whether the home team is ranked higher")
print("Accuracy: {0:.1f}%".format(np.mean(scores) * 100))

Using whether the home team is ranked higher
Accuracy: 56.6%

In [63]:
# Let's try see which team is better on the ladder. Using the previous year's ladder
ladder_filename = os.path.join(data_folder, "leagues_NBA_2013_standings_expanded-standings.csv")
ladder = pd.read_csv(ladder_filename,encoding = "ISO-8859-1",skiprows=[0])
#ladder.columns = ["RK","Team", "Overall", "Home", "Road", "E", "W", "A","C","SE","NW","P","SW","Pre","Post","<=3",">=10","Oct","Nov","Dec","Jan","Feb","Mar","Apr"]
ladder

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Rk</th>
      <th>Team</th>
      <th>Overall</th>
      <th>Home</th>
      <th>Road</th>
      <th>E</th>
      <th>W</th>
      <th>A</th>
      <th>C</th>
      <th>SE</th>
      <th>...</th>
      <th>Post</th>
      <th>¡Ü3</th>
      <th>¡Ý10</th>
      <th>Oct</th>
      <th>Nov</th>
      <th>Dec</th>
      <th>Jan</th>
      <th>Feb</th>
      <th>Mar</th>
      <th>Apr</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>Miami Heat</td>
      <td>66-16</td>
      <td>37-4</td>
      <td>29-12</td>
      <td>41-11</td>
      <td>25-5</td>
      <td>14-4</td>
      <td>12-6</td>
      <td>15-1</td>
      <td>...</td>
      <td>30-2</td>
      <td>9-3</td>
      <td>39-8</td>
      <td>1-0</td>
      <td>10-3</td>
      <td>10-5</td>
      <td>8-5</td>
      <td>12-1</td>
      <td>17-1</td>
      <td>8-1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>Oklahoma City Thunder</td>
      <td>60-22</td>
      <td>34-7</td>
      <td>26-15</td>
      <td>21-9</td>
      <td>39-13</td>
      <td>7-3</td>
      <td>8-2</td>
      <td>6-4</td>
      <td>...</td>
      <td>21-8</td>
      <td>3-6</td>
      <td>44-6</td>
      <td>NaN</td>
      <td>13-4</td>
      <td>11-2</td>
      <td>11-5</td>
      <td>7-4</td>
      <td>12-5</td>
      <td>6-2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>San Antonio Spurs</td>
      <td>58-24</td>
      <td>35-6</td>
      <td>23-18</td>
      <td>25-5</td>
      <td>33-19</td>
      <td>8-2</td>
      <td>9-1</td>
      <td>8-2</td>
      <td>...</td>
      <td>16-12</td>
      <td>9-5</td>
      <td>31-10</td>
      <td>1-0</td>
      <td>12-4</td>
      <td>12-4</td>
      <td>12-3</td>
      <td>8-3</td>
      <td>10-4</td>
      <td>3-6</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>Denver Nuggets</td>
      <td>57-25</td>
      <td>38-3</td>
      <td>19-22</td>
      <td>19-11</td>
      <td>38-14</td>
      <td>5-5</td>
      <td>10-0</td>
      <td>4-6</td>
      <td>...</td>
      <td>24-4</td>
      <td>11-7</td>
      <td>28-8</td>
      <td>0-1</td>
      <td>8-8</td>
      <td>9-6</td>
      <td>12-3</td>
      <td>8-4</td>
      <td>13-2</td>
      <td>7-1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>Los Angeles Clippers</td>
      <td>56-26</td>
      <td>32-9</td>
      <td>24-17</td>
      <td>21-9</td>
      <td>35-17</td>
      <td>7-3</td>
      <td>8-2</td>
      <td>6-4</td>
      <td>...</td>
      <td>17-9</td>
      <td>3-5</td>
      <td>38-12</td>
      <td>1-0</td>
      <td>8-6</td>
      <td>16-0</td>
      <td>9-7</td>
      <td>8-5</td>
      <td>7-7</td>
      <td>7-1</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>Memphis Grizzlies</td>
      <td>56-26</td>
      <td>32-9</td>
      <td>24-17</td>
      <td>22-8</td>
      <td>34-18</td>
      <td>8-2</td>
      <td>8-2</td>
      <td>6-4</td>
      <td>...</td>
      <td>23-8</td>
      <td>6-4</td>
      <td>28-9</td>
      <td>0-1</td>
      <td>12-1</td>
      <td>7-7</td>
      <td>10-7</td>
      <td>9-2</td>
      <td>11-6</td>
      <td>7-2</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>New York Knicks</td>
      <td>54-28</td>
      <td>31-10</td>
      <td>23-18</td>
      <td>37-15</td>
      <td>17-13</td>
      <td>10-6</td>
      <td>12-6</td>
      <td>15-3</td>
      <td>...</td>
      <td>22-10</td>
      <td>7-5</td>
      <td>31-12</td>
      <td>NaN</td>
      <td>11-4</td>
      <td>10-5</td>
      <td>7-6</td>
      <td>6-5</td>
      <td>12-6</td>
      <td>8-2</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>Brooklyn Nets</td>
      <td>49-33</td>
      <td>26-15</td>
      <td>23-18</td>
      <td>36-16</td>
      <td>13-17</td>
      <td>11-5</td>
      <td>13-5</td>
      <td>12-6</td>
      <td>...</td>
      <td>18-11</td>
      <td>9-4</td>
      <td>23-17</td>
      <td>NaN</td>
      <td>11-4</td>
      <td>5-11</td>
      <td>11-4</td>
      <td>7-5</td>
      <td>8-7</td>
      <td>7-2</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>Indiana Pacers</td>
      <td>49-32</td>
      <td>30-11</td>
      <td>19-21</td>
      <td>31-20</td>
      <td>18-12</td>
      <td>6-11</td>
      <td>13-3</td>
      <td>12-6</td>
      <td>...</td>
      <td>17-11</td>
      <td>4-9</td>
      <td>27-14</td>
      <td>1-0</td>
      <td>7-8</td>
      <td>10-5</td>
      <td>9-6</td>
      <td>9-3</td>
      <td>11-5</td>
      <td>2-5</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>Golden State Warriors</td>
      <td>47-35</td>
      <td>28-13</td>
      <td>19-22</td>
      <td>19-11</td>
      <td>28-24</td>
      <td>7-3</td>
      <td>5-5</td>
      <td>7-3</td>
      <td>...</td>
      <td>17-13</td>
      <td>5-3</td>
      <td>20-18</td>
      <td>1-0</td>
      <td>8-6</td>
      <td>12-4</td>
      <td>8-7</td>
      <td>4-8</td>
      <td>9-7</td>
      <td>5-3</td>
    </tr>
    <tr>
      <th>10</th>
      <td>11</td>
      <td>Chicago Bulls</td>
      <td>45-37</td>
      <td>24-17</td>
      <td>21-20</td>
      <td>34-18</td>
      <td>11-19</td>
      <td>13-5</td>
      <td>9-7</td>
      <td>12-6</td>
      <td>...</td>
      <td>15-15</td>
      <td>11-7</td>
      <td>16-16</td>
      <td>1-0</td>
      <td>6-7</td>
      <td>9-6</td>
      <td>12-4</td>
      <td>5-8</td>
      <td>7-7</td>
      <td>5-5</td>
    </tr>
    <tr>
      <th>11</th>
      <td>12</td>
      <td>Houston Rockets</td>
      <td>45-37</td>
      <td>29-12</td>
      <td>16-25</td>
      <td>21-9</td>
      <td>24-28</td>
      <td>7-3</td>
      <td>7-3</td>
      <td>7-3</td>
      <td>...</td>
      <td>16-11</td>
      <td>5-5</td>
      <td>26-13</td>
      <td>1-0</td>
      <td>6-8</td>
      <td>10-6</td>
      <td>8-9</td>
      <td>6-5</td>
      <td>9-5</td>
      <td>5-4</td>
    </tr>
    <tr>
      <th>12</th>
      <td>13</td>
      <td>Los Angeles Lakers</td>
      <td>45-37</td>
      <td>29-12</td>
      <td>16-25</td>
      <td>17-13</td>
      <td>28-24</td>
      <td>6-4</td>
      <td>6-4</td>
      <td>5-5</td>
      <td>...</td>
      <td>20-8</td>
      <td>8-5</td>
      <td>18-17</td>
      <td>0-2</td>
      <td>8-6</td>
      <td>7-7</td>
      <td>5-11</td>
      <td>9-4</td>
      <td>9-6</td>
      <td>7-1</td>
    </tr>
    <tr>
      <th>13</th>
      <td>14</td>
      <td>Atlanta Hawks</td>
      <td>44-38</td>
      <td>25-16</td>
      <td>19-22</td>
      <td>29-23</td>
      <td>15-15</td>
      <td>7-11</td>
      <td>11-7</td>
      <td>11-5</td>
      <td>...</td>
      <td>15-16</td>
      <td>5-5</td>
      <td>19-20</td>
      <td>NaN</td>
      <td>9-5</td>
      <td>10-5</td>
      <td>7-9</td>
      <td>7-4</td>
      <td>8-10</td>
      <td>3-5</td>
    </tr>
    <tr>
      <th>14</th>
      <td>15</td>
      <td>Utah Jazz</td>
      <td>43-39</td>
      <td>30-11</td>
      <td>13-28</td>
      <td>17-13</td>
      <td>26-26</td>
      <td>5-5</td>
      <td>5-5</td>
      <td>7-3</td>
      <td>...</td>
      <td>13-15</td>
      <td>5-7</td>
      <td>19-21</td>
      <td>1-0</td>
      <td>8-8</td>
      <td>6-9</td>
      <td>10-4</td>
      <td>6-6</td>
      <td>7-9</td>
      <td>5-3</td>
    </tr>
    <tr>
      <th>15</th>
      <td>16</td>
      <td>Boston Celtics</td>
      <td>41-40</td>
      <td>27-13</td>
      <td>14-27</td>
      <td>27-24</td>
      <td>14-16</td>
      <td>7-9</td>
      <td>8-9</td>
      <td>12-6</td>
      <td>...</td>
      <td>13-16</td>
      <td>8-7</td>
      <td>18-23</td>
      <td>0-1</td>
      <td>9-6</td>
      <td>5-9</td>
      <td>8-7</td>
      <td>8-4</td>
      <td>8-8</td>
      <td>3-5</td>
    </tr>
    <tr>
      <th>16</th>
      <td>17</td>
      <td>Dallas Mavericks</td>
      <td>41-41</td>
      <td>24-17</td>
      <td>17-24</td>
      <td>17-13</td>
      <td>24-28</td>
      <td>5-5</td>
      <td>6-4</td>
      <td>6-4</td>
      <td>...</td>
      <td>18-12</td>
      <td>5-8</td>
      <td>17-19</td>
      <td>1-1</td>
      <td>6-8</td>
      <td>5-10</td>
      <td>7-8</td>
      <td>6-5</td>
      <td>11-5</td>
      <td>5-4</td>
    </tr>
    <tr>
      <th>17</th>
      <td>18</td>
      <td>Milwaukee Bucks</td>
      <td>38-44</td>
      <td>21-20</td>
      <td>17-24</td>
      <td>24-28</td>
      <td>14-16</td>
      <td>11-7</td>
      <td>7-9</td>
      <td>6-12</td>
      <td>...</td>
      <td>12-19</td>
      <td>7-5</td>
      <td>13-25</td>
      <td>NaN</td>
      <td>7-7</td>
      <td>9-6</td>
      <td>8-7</td>
      <td>4-8</td>
      <td>7-9</td>
      <td>3-7</td>
    </tr>
    <tr>
      <th>18</th>
      <td>19</td>
      <td>Philadelphia 76ers</td>
      <td>34-48</td>
      <td>23-18</td>
      <td>11-30</td>
      <td>22-30</td>
      <td>12-18</td>
      <td>7-9</td>
      <td>7-11</td>
      <td>8-10</td>
      <td>...</td>
      <td>12-19</td>
      <td>4-5</td>
      <td>13-24</td>
      <td>1-0</td>
      <td>9-6</td>
      <td>4-11</td>
      <td>5-9</td>
      <td>3-8</td>
      <td>8-9</td>
      <td>4-5</td>
    </tr>
    <tr>
      <th>19</th>
      <td>20</td>
      <td>Toronto Raptors</td>
      <td>34-48</td>
      <td>21-20</td>
      <td>13-28</td>
      <td>22-30</td>
      <td>12-18</td>
      <td>5-11</td>
      <td>8-10</td>
      <td>9-9</td>
      <td>...</td>
      <td>13-16</td>
      <td>8-8</td>
      <td>16-22</td>
      <td>0-1</td>
      <td>4-12</td>
      <td>7-7</td>
      <td>5-10</td>
      <td>7-5</td>
      <td>4-11</td>
      <td>7-2</td>
    </tr>
    <tr>
      <th>20</th>
      <td>21</td>
      <td>Portland Trail Blazers</td>
      <td>33-49</td>
      <td>22-19</td>
      <td>11-30</td>
      <td>15-15</td>
      <td>18-34</td>
      <td>5-5</td>
      <td>5-5</td>
      <td>5-5</td>
      <td>...</td>
      <td>8-21</td>
      <td>9-6</td>
      <td>13-24</td>
      <td>1-0</td>
      <td>5-10</td>
      <td>9-4</td>
      <td>8-8</td>
      <td>3-9</td>
      <td>7-9</td>
      <td>0-9</td>
    </tr>
    <tr>
      <th>21</th>
      <td>22</td>
      <td>Minnesota Timberwolves</td>
      <td>31-51</td>
      <td>20-21</td>
      <td>11-30</td>
      <td>14-16</td>
      <td>17-35</td>
      <td>4-6</td>
      <td>7-3</td>
      <td>3-7</td>
      <td>...</td>
      <td>12-20</td>
      <td>3-10</td>
      <td>15-26</td>
      <td>NaN</td>
      <td>7-8</td>
      <td>7-5</td>
      <td>3-12</td>
      <td>3-10</td>
      <td>6-11</td>
      <td>5-5</td>
    </tr>
    <tr>
      <th>22</th>
      <td>23</td>
      <td>Detroit Pistons</td>
      <td>29-53</td>
      <td>18-23</td>
      <td>11-30</td>
      <td>25-27</td>
      <td>4-26</td>
      <td>6-12</td>
      <td>8-8</td>
      <td>11-7</td>
      <td>...</td>
      <td>8-20</td>
      <td>6-10</td>
      <td>15-29</td>
      <td>0-1</td>
      <td>5-11</td>
      <td>6-10</td>
      <td>6-7</td>
      <td>6-8</td>
      <td>1-13</td>
      <td>5-3</td>
    </tr>
    <tr>
      <th>23</th>
      <td>24</td>
      <td>Washington Wizards</td>
      <td>29-53</td>
      <td>22-19</td>
      <td>7-34</td>
      <td>15-37</td>
      <td>14-16</td>
      <td>5-13</td>
      <td>5-13</td>
      <td>5-11</td>
      <td>...</td>
      <td>14-17</td>
      <td>6-9</td>
      <td>13-17</td>
      <td>0-1</td>
      <td>1-12</td>
      <td>3-11</td>
      <td>7-9</td>
      <td>7-5</td>
      <td>9-8</td>
      <td>2-7</td>
    </tr>
    <tr>
      <th>24</th>
      <td>25</td>
      <td>Sacramento Kings</td>
      <td>28-54</td>
      <td>20-21</td>
      <td>8-33</td>
      <td>14-16</td>
      <td>14-38</td>
      <td>4-6</td>
      <td>4-6</td>
      <td>6-4</td>
      <td>...</td>
      <td>9-19</td>
      <td>7-3</td>
      <td>12-31</td>
      <td>0-1</td>
      <td>4-10</td>
      <td>7-8</td>
      <td>6-11</td>
      <td>3-9</td>
      <td>7-8</td>
      <td>1-7</td>
    </tr>
    <tr>
      <th>25</th>
      <td>26</td>
      <td>New Orleans Hornets</td>
      <td>27-55</td>
      <td>16-25</td>
      <td>11-30</td>
      <td>12-18</td>
      <td>15-37</td>
      <td>3-7</td>
      <td>5-5</td>
      <td>4-6</td>
      <td>...</td>
      <td>8-21</td>
      <td>7-5</td>
      <td>10-27</td>
      <td>0-1</td>
      <td>4-9</td>
      <td>3-13</td>
      <td>8-8</td>
      <td>5-8</td>
      <td>6-9</td>
      <td>1-7</td>
    </tr>
    <tr>
      <th>26</th>
      <td>27</td>
      <td>Phoenix Suns</td>
      <td>25-57</td>
      <td>17-24</td>
      <td>8-33</td>
      <td>8-22</td>
      <td>17-35</td>
      <td>1-9</td>
      <td>4-6</td>
      <td>3-7</td>
      <td>...</td>
      <td>8-21</td>
      <td>6-8</td>
      <td>10-31</td>
      <td>0-1</td>
      <td>7-9</td>
      <td>4-11</td>
      <td>5-9</td>
      <td>4-9</td>
      <td>3-12</td>
      <td>2-6</td>
    </tr>
    <tr>
      <th>27</th>
      <td>28</td>
      <td>Cleveland Cavaliers</td>
      <td>24-58</td>
      <td>14-27</td>
      <td>10-31</td>
      <td>18-34</td>
      <td>6-24</td>
      <td>5-13</td>
      <td>3-13</td>
      <td>10-8</td>
      <td>...</td>
      <td>8-21</td>
      <td>6-11</td>
      <td>7-27</td>
      <td>1-0</td>
      <td>3-12</td>
      <td>3-13</td>
      <td>6-8</td>
      <td>7-5</td>
      <td>2-12</td>
      <td>2-8</td>
    </tr>
    <tr>
      <th>28</th>
      <td>29</td>
      <td>Charlotte Bobcats</td>
      <td>21-61</td>
      <td>15-26</td>
      <td>6-35</td>
      <td>18-34</td>
      <td>3-27</td>
      <td>6-12</td>
      <td>6-12</td>
      <td>6-10</td>
      <td>...</td>
      <td>9-21</td>
      <td>6-6</td>
      <td>6-37</td>
      <td>NaN</td>
      <td>7-8</td>
      <td>1-15</td>
      <td>3-11</td>
      <td>2-10</td>
      <td>4-12</td>
      <td>4-5</td>
    </tr>
    <tr>
      <th>29</th>
      <td>30</td>
      <td>Orlando Magic</td>
      <td>20-62</td>
      <td>12-29</td>
      <td>8-33</td>
      <td>10-42</td>
      <td>10-20</td>
      <td>2-16</td>
      <td>5-13</td>
      <td>3-13</td>
      <td>...</td>
      <td>5-25</td>
      <td>2-9</td>
      <td>8-30</td>
      <td>NaN</td>
      <td>5-10</td>
      <td>7-9</td>
      <td>2-12</td>
      <td>2-11</td>
      <td>3-13</td>
      <td>1-7</td>
    </tr>
  </tbody>
</table>
<p>30 rows × 24 columns</p>
</div>

In [67]:
# We can create a new feature -- HomeTeamRanksHigher\
results["HomeTeamRanksHigher"] = 0
for index, row in results.iterrows():
    home_team = row["Home Team"]
    visitor_team = row["Visitor Team"]
    if home_team == "New Orleans Pelicans":
        home_team = "New Orleans Hornets"
    elif visitor_team == "New Orleans Pelicans":
        visitor_team = "New Orleans Hornets"
    home_rank = ladder[ladder["Team"] == home_team]["Rk"].values[0]
    visitor_rank = ladder[ladder["Team"] == visitor_team]["Rk"].values[0]
    row["HomeTeamRanksHigher"] = int(home_rank > visitor_rank)
    results.ix[index] = row
results[:5]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Score Type</th>
      <th>Visitor Team</th>
      <th>VisitorPts</th>
      <th>Home Team</th>
      <th>HomePts</th>
      <th>OT?</th>
      <th>Notes</th>
      <th>HomeWin</th>
      <th>HomeLastWin</th>
      <th>VisitorLastWin</th>
      <th>HomeWinStreak</th>
      <th>VisitorWinStreak</th>
      <th>HomeTeamRanksHigher</th>
      <th>HomeTeamWonLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2014-06-05</td>
      <td>9:00 PM</td>
      <td>Miami Heat</td>
      <td>95</td>
      <td>San Antonio Spurs</td>
      <td>110</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>False</td>
      <td>False</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2014-06-08</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>98</td>
      <td>San Antonio Spurs</td>
      <td>96</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>True</td>
      <td>False</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2014-06-10</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>111</td>
      <td>Miami Heat</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>True</td>
      <td>False</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2014-06-12</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>107</td>
      <td>Miami Heat</td>
      <td>86</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
      <td>True</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2014-06-15</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>87</td>
      <td>San Antonio Spurs</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>True</td>
      <td>False</td>
      <td>2</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>

In [68]:
X_homehigher =  results[["HomeLastWin", "VisitorLastWin", "HomeTeamRanksHigher"]].values
clf = DecisionTreeClassifier(random_state=14)
scores = cross_val_score(clf, X_homehigher, y_true, scoring='accuracy')
print("Using whether the home team is ranked higher")
print("Accuracy: {0:.1f}%".format(np.mean(scores) * 100))

Using whether the home team is ranked higher
Accuracy: 60.0%

In [69]:
from sklearn.grid_search import GridSearchCV

parameter_space = {
                   "max_depth": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                   }
clf = DecisionTreeClassifier(random_state=14)
grid = GridSearchCV(clf, parameter_space)
grid.fit(X_homehigher, y_true)
print("Accuracy: {0:.1f}%".format(grid.best_score_ * 100))

E:\Anaconda3\envs\DataMining\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

Accuracy: 60.0%

In [70]:
# Who won the last match? We ignore home/visitor for this bit
last_match_winner = defaultdict(int)
results["HomeTeamWonLast"] = 0

for index, row in results.iterrows():
    home_team = row["Home Team"]
    visitor_team = row["Visitor Team"]
    teams = tuple(sorted([home_team, visitor_team]))  # Sort for a consistent ordering
    # Set in the row, who won the last encounter
    row["HomeTeamWonLast"] = 1 if last_match_winner[teams] == row["Home Team"] else 0
    results.ix[index] = row
    # Who won this one?
    winner = row["Home Team"] if row["HomeWin"] else row["Visitor Team"]
    last_match_winner[teams] = winner
results.ix[:5]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Score Type</th>
      <th>Visitor Team</th>
      <th>VisitorPts</th>
      <th>Home Team</th>
      <th>HomePts</th>
      <th>OT?</th>
      <th>Notes</th>
      <th>HomeWin</th>
      <th>HomeLastWin</th>
      <th>VisitorLastWin</th>
      <th>HomeWinStreak</th>
      <th>VisitorWinStreak</th>
      <th>HomeTeamRanksHigher</th>
      <th>HomeTeamWonLast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2014-06-05</td>
      <td>9:00 PM</td>
      <td>Miami Heat</td>
      <td>95</td>
      <td>San Antonio Spurs</td>
      <td>110</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>False</td>
      <td>False</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2014-06-08</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>98</td>
      <td>San Antonio Spurs</td>
      <td>96</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>True</td>
      <td>False</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2014-06-10</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>111</td>
      <td>Miami Heat</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>True</td>
      <td>False</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2014-06-12</td>
      <td>9:00 PM</td>
      <td>San Antonio Spurs</td>
      <td>107</td>
      <td>Miami Heat</td>
      <td>86</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
      <td>True</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2014-06-15</td>
      <td>8:00 PM</td>
      <td>Miami Heat</td>
      <td>87</td>
      <td>San Antonio Spurs</td>
      <td>104</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>True</td>
      <td>True</td>
      <td>False</td>
      <td>2</td>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2014-05-01</td>
      <td>7:00 PM</td>
      <td>Indiana Pacers</td>
      <td>95</td>
      <td>Atlanta Hawks</td>
      <td>88</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>

In [71]:
X_home_higher =  results[["HomeTeamRanksHigher", "HomeTeamWonLast"]].values
clf = DecisionTreeClassifier(random_state=14)
scores = cross_val_score(clf, X_home_higher, y_true, scoring='accuracy')
print("Using whether the home team is ranked higher")
print("Accuracy: {0:.1f}%".format(np.mean(scores) * 100))

Using whether the home team is ranked higher
Accuracy: 58.8%

In [72]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
encoding = LabelEncoder()
encoding.fit(results["Home Team"].values)
home_teams = encoding.transform(results["Home Team"].values)
visitor_teams = encoding.transform(results["Visitor Team"].values)
X_teams = np.vstack([home_teams, visitor_teams]).T

onehot = OneHotEncoder()
X_teams = onehot.fit_transform(X_teams).todense()

clf = DecisionTreeClassifier(random_state=14)
scores = cross_val_score(clf, X_teams, y_true, scoring='accuracy')
print("Accuracy: {0:.1f}%".format(np.mean(scores) * 100))

Accuracy: 59.0%

In [73]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=14)
scores = cross_val_score(clf, X_teams, y_true, scoring='accuracy')
print("Using full team labels is ranked higher")
print("Accuracy: {0:.1f}%".format(np.mean(scores) * 100))

Using full team labels is ranked higher
Accuracy: 60.9%

In [74]:
X_all = np.hstack([X_home_higher, X_teams])
print(X_all.shape)

(1319, 62)

In [75]:
clf = RandomForestClassifier(random_state=14)
scores = cross_val_score(clf, X_all, y_true, scoring='accuracy')
print("Using whether the home team is ranked higher")
print("Accuracy: {0:.1f}%".format(np.mean(scores) * 100))

Using whether the home team is ranked higher
Accuracy: 58.2%

In [76]:
#n_estimators=10, criterion='gini', max_depth=None, 
#min_samples_split=2, min_samples_leaf=1,
#max_features='auto',
#max_leaf_nodes=None, bootstrap=True,
#oob_score=False, n_jobs=1,
#random_state=None, verbose=0, min_density=None, compute_importances=None
parameter_space = {
                   "max_features": [2, 10, 'auto'],
                   "n_estimators": [100,],
                   "criterion": ["gini", "entropy"],
                   "min_samples_leaf": [2, 4, 6],
                   }
clf = RandomForestClassifier(random_state=14)
grid = GridSearchCV(clf, parameter_space)
grid.fit(X_all, y_true)
print("Accuracy: {0:.1f}%".format(grid.best_score_ * 100))
print(grid.best_estimator_)

Accuracy: 64.4%
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=6, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=14, verbose=0, warm_start=False)